add loudness_detect
nomalab/stainless-ffmpeg pull request #21
Opened 2022-03-08 14:26 UTC by Bramart

nomalab/nomalab#3584

2022-05-10 16:53 UTC, Romanelaf requested changes

2022-05-10 16:53 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +use std::option::Option::*;
pas besoin d'importer ça

2022-05-10 16:53 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +  let metadata_param = ParameterValue::String("true".to_string());
pour le type boolean il y a `ParameterValue::Bool(true)`

2022-05-10 16:53 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +          aformat_output.push(FilterOutput {
comme il n'y a qu'un élément (il ne passe pas dans une boucle), tu peux direct le mettre dans le Filter "aformat" plus bas
```
outputs: Some(vec![FilterOutput {
  stream_label: output_label,
}]),
```

2022-05-10 16:53 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +            let mut tpk;
pas besoin de déclarer ces 3 variables en dehors de ta boucle, et `str_tpk_key` et `energy` n'ont pas besoin d'être mutable

2023-01-24 10:36 UTC, Romanelaf requested changes
rebase aussi

2023-01-24 10:36 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +          let mut keys_vec = vec!["lavfi.r128.I".to_string(), "lavfi.r128.LRA".to_string()];
```suggestion
          let mut lavfi_keys = vec!["lavfi.r128.I".to_string(), "lavfi.r128.LRA".to_string()];
```

2023-02-02 14:15 UTC, Bramart commented on src/probe/loudness_detect.rs
> +            for ch in 0..channel {
Toujours dans la boucle : 
`if !lavfi_keys.contains(&key) {
     lavfi_keys.push(key);
}`
C'est ok ? parce qu'on est quand même obligé de parcourir cette boucle pour avoir le nombre de channels

2023-02-09 09:50 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +            for ch in 0..channel {
ok !

2023-02-09 10:03 UTC, Romanelaf commented on src/probe/loudness_detect.rs
> +            for ch in 0..channel {
enfin en fait toute la partie : 
```
if pair.len() == 1 {
  channel = track.channel;
} else {
  channel = pair.len() as u8;
}
for ch in 0..channel {
  let key = format!("lavfi.r128.true_peaks_ch{}", ch);
  keys_vec.push(key);
}
```
peut être sortie de la boucle for track in pair.
faut juste modifier le `track` dans le premier if par `pair[0]`

2023-03-13 18:50 UTC, Romanelaf approved these changes

2023-03-17 09:51 UTC, merged