add check color informations : color matrix, color space, color trans…
nomalab/stainless-ffmpeg pull request #24
Opened 2022-04-08 15:39 UTC by Bramart

…fer characteristic

2022-04-13 09:43 UTC, Bramart commented
nomalab/nomalab#4241

2022-04-22 15:26 UTC, Romanelaf requested changes

2022-04-22 15:26 UTC, Romanelaf commented on src/probe/deep.rs
> +impl Default for StreamProbeResult {
je pense pas que ce soit nécessaire de l'implémenter, et sinon tu peux utiliser direct le derive `Default` à la déclaration de la structure : 
#[derive(Clone, Debug, **Default**, Deserialize, PartialEq, Serialize)]

2022-05-11 15:05 UTC, Romanelaf requested changes

2022-05-19 13:00 UTC, Romanelaf approved these changes

2022-05-20 16:36 UTC, Romanelaf approved these changes

2022-05-24 10:14 UTC, merged