add media offline detection with OCR filter
nomalab/stainless-ffmpeg pull request #31
Opened 2023-01-05 13:11 UTC by Bramart

nomalab/nomalab#4508

2023-01-19 16:53 UTC, Romanelaf requested changes

2023-01-19 16:53 UTC, Romanelaf commented on src/probe/ocr_detect.rs
> +        "lavfi.scd.score".to_string(),
pas besoin de sortir cette valeur a priori

2023-01-30 08:21 UTC, Bramart commented on examples/deep_probe.rs
> +      th: Some(0.00),
afin d'avoir le même nombre de chiffres après la virgule

2023-02-01 16:14 UTC, Romanelaf approved these changes

2023-02-02 11:25 UTC, merged