Fix deep probe audio
nomalab/stainless-ffmpeg pull request #44
Opened 2023-08-09 17:11 UTC by Romanelaf

nomalab/nomalab#4520

2023-11-13 14:25 UTC, Bramart requested changes

2023-11-13 14:25 UTC, Bramart commented on src/probe/sine_detect.rs
> +                range_value = match sample_fmt.as_str() {
avec `av_get_bytes_per_sample(sample_format)` https://ffmpeg.org/doxygen/6.0/group__lavu__sampfmts.html#ga0c3c218e1dd570ad4917c69a35a6c77d
ca prendrait en compte tous les sample format de ffmpeg
et ensuite on pourrait match sur le nombre d'octets :
`"2" => i16::MAX as f64,
 "4" => i32::MAX as f64,
 "8" => i64::MAX as f64,
`
et ca detecte bien le s32 (24 bit) comme du 32 bits

2023-11-20 13:46 UTC, Romanelaf commented on src/probe/sine_detect.rs
> +                range_value = match sample_fmt.as_str() {
alors il me semble que pour le float (sample format du aac par exemple) le range c'est 1

2023-11-20 14:54 UTC, Bramart approved these changes

2023-11-20 17:53 UTC, merged