Update scene detect
nomalab/stainless-ffmpeg pull request #54
Opened 2024-02-09 14:05 UTC by Bramart

nomalab/nomalab#4845

2024-02-13 08:49 UTC, Romanelaf requested changes

2024-02-13 08:49 UTC, Romanelaf commented on src/probe/scene_detect.rs
> +          detected_scene.insert(
je mettrais plutôt un init au début (dans le premier `for index in video_indexes`)

2024-02-13 08:49 UTC, Romanelaf commented on src/probe/scene_detect.rs
> +              scene.frame_start = (value.parse::<f32>().unwrap() * video_details.frame_rate) as i64;
ça tu peux le passer direct dans l'init de `scene`, le `frames_length` aussi tu peux l'init à ce moment là

2024-02-13 08:49 UTC, Romanelaf commented on src/probe/scene_detect.rs
> +              scene.index = scene_count;
sans avoir à utiliser un scene_count, dans le `if let Some(last_detect) = detected_scene.last_mut()` tu peux incrémenter ton `scene.index` à partir du `last_detect.index`

2024-02-13 13:26 UTC, Bramart commented on src/probe/scene_detect.rs
> +              scene.frame_start = (value.parse::<f32>().unwrap() * video_details.frame_rate) as i64;
le frames length je pense pas, il se base sur le frame end qui est définit avec le last detect, donc obligé d'attendre la scène d'après pour le définir

2024-02-13 13:34 UTC, Romanelaf commented on src/probe/scene_detect.rs
> +              scene.frame_start = (value.parse::<f32>().unwrap() * video_details.frame_rate) as i64;
ouais j'ai mal exprimé mon point, c'était surtout pour pas avoir à refaire une boucle à la fin pour ajouter le frame length du dernier plan, donc on peut l'init ici en se basant sur la durée totale et le modifier dans tous les cas dans la boucle last_mut

2024-02-14 10:47 UTC, Romanelaf requested changes

2024-02-15 08:56 UTC, Romanelaf approved these changes

2024-02-16 10:38 UTC, merged